### ISSUE TITLE
Archetype Build Problem - Groovy Dependency

### ISSUE THREAD

**Issue by rson25** [adobe/aem-project-archetype#377] opened 2020-04-20 19:29 UTC
### Expected Behaviour

Running the following command should create a new AEM SPA project and successfully execute the build:

`mvn -B archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=23 -DaemVersion=6.4.8 -DappTitle="My SPA Site" -DappId="spasite" -DgroupId="com.spasite" -DfrontendModule=angular -DincludeExamples=n`

### Actual Behaviour

During the build process the step "Executing META-INF/archetype-post-generate.groovy post-generation script" hangs for a bit, then the build fails with the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: startup failed:

[ERROR] General error during conversion: Error grabbing Grapes -- [unresolved dependency: org.codehaus.groovy#groovy-all;2.4.8: not found]

[ERROR] java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: org.codehaus.groovy#groovy-all;2.4.8: not found]
```

 #### Steps to Reproduce

Run the following command in a command window to create a new project:

`mvn -B archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=23 -DaemVersion=6.4.8 -DappTitle="My SPA Site" -DappId="spasite" -DgroupId="com.spasite" -DfrontendModule=angular -DincludeExamples=n`

#### Platform and Version
mvn: 3.6.3
AEM: 6.4.8
Java: 1.8

**Comment by brunob15** [comment] 2020-08-20 19:33
@rson25 how did you solve it?

**Comment by msagolj** [comment] 2020-08-28 09:30
This issues doesn't seem to be related to the archetype , see:
https://stackoverflow.com/questions/16871792/groovy-grab-download-failed

So closing this issue for now. Reopen if you think this issue needs to be solved inside the archetype project itself.

**Closed by msagolj** 2020-08-28 09:30 UTC

**Comment by fahol-coop** [comment] 2021-04-07 14:38
this should be fixed in archetype. What kind of archetype is this, if it's not working initially? it's useless. delete it or fix it!

**Comment by pavrda** [comment] 2022-10-31 17:50
In my case the problem was caused by groovy. In this step groovy-all package is downloaded. But because problems on jcenter.bintray.com download was not successful. Unfortunately the log does not tell you what the true problem is.

I manually installed groovy framework and tried to install the dependency manually: `grape -V resolve org.codehaus.groovy groovy-all 2.4.8` 

It didn't work too, but were more verbose about what was wrong:
`ERROR: SERVER ERROR: Gateway Time-out url=https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.8/groovy-all-2.4.8.jar.sha1`

Trying again and again I got several error types. The server was very creative in this case.
The dependency could also be downloaded from another repository or using another way.
