### ISSUE TITLE
Cannot add components to default home page - built using React frontend

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-project-archetype#371] opened 2020-04-13 18:57 UTC
### Expected Behaviour
Project built with Archetype 23, with react as frontend, should allow users to add components to sample pages. 

### Actual Behaviour
Project built with Archetype 23, with react as frontend, does not allow users to add components to sample pages. 

When we drag-drop a default/ootb/General component, the component does not show up. Browser console shows an error message.

Erro in browser console: 
`granite.js:266 GET http://localhost:4502/mnt/overlay/wcm/core/content/editor/_jcr_content/content/items/content/content/items/styleselector.form.html/content/hero-site/us/en/home/_jcr_content/root/responsivegrid/*/ 403 (Forbidden)`

![Screen_Shot_2020-04-13_at_1_45_45_PM](https://user-images.githubusercontent.com/902972/79150065-be9c5a80-7d8d-11ea-883c-22314b8e575a.png)

### Reproduce Scenario (including but not limited to)
1. Create new project
```
 mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=6.5.0 \
 -D appTitle="Hero Site" \
 -D appId="hero-site" \
 -D groupId="com.hero.aem" \
 -D frontendModule=react \
 -D includeExamples=n
```
2. Build and deploy to AEM 6.5
```
$ cd hero-site
$ mvn clean install -PautoInstallPackage
```
3. Go to edit the default home page, and choose Edit
AEM > Sites > Hero Site > us en > home
or
http://localhost:4502/editor.html/content/hero-site/us/en/home.html

#### Steps to Reproduce
Documented above.

#### Platform and Version
- AEM 6.5
  - Reproducible on both AEM 6.5.2 and 6.5.4
  - With ACS Commons 4.5.0
- NPM v6.13.4
- Node v12.16.1
- Java 1.8.0_221

#### Logs taken while reproducing problem

**Comment by godanny86** [comment] 2020-04-13 19:40
@ksurendra this might be a duplicate of an issue i filed earlier: https://github.com/adobe/aem-project-archetype/issues/366. AFAICT only the **Text** component is set up to work w/ React and Angular front-end on a clean generation of a project...

**Comment by ksurendra** [comment] 2020-04-13 19:50
Thanks @godanny86 . I tried, cannot add Text component as well.

**Comment by godanny86** [comment] 2020-04-13 20:53
correct, thats why i filed the bug #366 :) However even with the correct policy, only the Text component will work.

**Comment by bpauli** [comment] 2020-05-25 09:11
fixed in https://github.com/adobe/aem-project-archetype/commit/6978b1f890a14c46aa476aa8f5ca9bd6ad8de798

**Closed by bpauli** 2020-05-25 09:11 UTC
