### ISSUE TITLE
artifactId is not appId value when it's not explicitly provided, but literally becomes ${appId}

### ISSUE THREAD

**Issue by puradawid** [adobe/aem-project-archetype#374] opened 2020-04-15 19:45 UTC
### Expected Behaviour

When using batch mode of `archetype:generate` provided by `README.md`:

```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=cloud \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=general \
 -D includeExamples=n
```

it should create folder named `mysite` and change all `artifactId` occurences into `appId` to all references in generated project.

### Actual Behaviour

When using batch mode of `archetype:generate` provided by `README.md`:

```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=cloud \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=general \
 -D includeExamples=n
```

it creates archetype literally in `${appId}` folder, which is unexpected behavior given the current documentation - `artifactId` should be the same as `appId` value. All other references for `artifactId` are literally changed into `${appId}`. The workaround is to use interactive mode (i.e. not use `-B` flag) which asks for `artifactId` and user can provide correct name (however it still hints `${appId}).

#### Platform and Version

* Ubuntu Linux 18.04 
* Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
* openjdk version "11.0.6" 2020-01-14
* reproducible on 23 and also 24-SNAPSHOT (current master branch)

**Comment by msagolj** [comment] 2020-08-27 09:37
@puradawid tested with your above batch command using latest 24-SNAPSHOT and it correctly generated a `mysite` folder. I also searched the generated project for any occurrences of `${appId}` and couldn't find any. So it looks like this issue got resolved meanwhile. So I'm closing the issue, please reopen if you can still reproduce the issue.

**Closed by msagolj** 2020-08-27 09:37 UTC
