### ISSUE TITLE
Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8

### ISSUE THREAD

**Issue by ziad-mesalmi** [adobe/aem-project-archetype#861] opened 2022-01-04 12:07 UTC
When creating a new project with this command:
mvn -B archetype:generate -D archetypeGroupId=com.adobe.aem -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=33 -D appTitle="WKND Sites Project" -D appId="wknd" -D groupId="com.adobe.aem.guides.wknd" -D artifactId="aem-guides-wknd" -D version="0.0.1-SNAPSHOT" -D aemVersion="6.5.6"
### Expected Behaviour
Project succeffuly created 

### Actual Behaviour
Build Failure
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: startup failed:
[ERROR] General error during conversion: Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8
[ERROR]
[ERROR] groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8
[ERROR]         at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:529)
[ERROR]         at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:81)
[ERROR]         at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerExtensionModuleFromProperties(MetaClassRegistryImpl.java:174)
[ERROR]         at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$registerExtensionModuleFromProperties.call(Unknown Source)
[ERROR]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[ERROR]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[ERROR]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
[ERROR]         at groovy.grape.GrapeIvy.processCategoryMethods(GrapeIvy.groovy:290)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

#### Logs taken while reproducing problem

**Comment by kwin** [comment] 2022-01-04 12:10
This seems to be a duplicate of #857

**Comment by ziad-mesalmi** [comment] 2022-01-04 12:42
@kwin Thanks, but i seen that this fix https://github.com/stefanseifert/aem-project-archetype/commit/13d4999327e3b8c6b7d5eb1af19f11abcf8b39ef is not present in the last release?

**Comment by cziegeler** [comment] 2022-01-05 12:42
Closing as duplicate of #857

**Closed by cziegeler** 2022-01-05 12:42 UTC
